### ISSUE TITLE
Pinata CI

### ISSUE THREAD

**Issue by samoht** [docker/datakit#25]
This is the tracking issue for the Pinata CI requirements. /cc @MagnusS 

The short-term new features that are needed to deploy a local Datakit instance for CI purposes are:

- [x] a pipeline syntax (#24)
- [x] a way to express Git remotes (#21)
- [x] a way to interact with Github API (#19) and repositories (#20)
- [ ] a way to interact with S3 (#20)

**Comment by talex5** [comment]
We now have a Pinata CI as a separate project, so closing this.
